version: "3.9"

services:
  bbstatsy:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    init: true
    security_opt: 
      - seccomp=chrome.json
    volumes:
      - /bbstatsy/node_modules
      - /bbstatsy/.yarn-cache